"""Shared ToolTask lifecycle constants."""

PENDING = "pending"
RUNNING = "running"
COMPLETED = "completed"
FAILED = "failed"
CANCELLED = "cancelled"
REJECTED = "rejected"

ACTIVE_TASK_STATUSES = (PENDING, RUNNING, COMPLETED)
TERMINAL_TASK_STATUSES = (COMPLETED, FAILED, CANCELLED, REJECTED)
VALID_TASK_STATUSES = (
    PENDING,
    RUNNING,
    COMPLETED,
    FAILED,
    CANCELLED,
    REJECTED,
)

NOT_REQUIRED = "not_required"
PENDING_APPROVAL = "pending_approval"
APPROVED = "approved"
APPROVAL_REJECTED = "rejected"

EXECUTABLE_APPROVAL_STATUSES = (NOT_REQUIRED, APPROVED)
VALID_APPROVAL_STATUSES = (
    NOT_REQUIRED,
    PENDING_APPROVAL,
    APPROVED,
    APPROVAL_REJECTED,
)
